# Generated by Django 5.2.1 on 2025-05-13 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
        ("wiki", "0002_alter_articlecategory_options_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user_management.profile",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="header_image",
            field=models.ImageField(blank=True, null=True, upload_to="wiki_headers/"),
        ),
    ]
