# Generated by Django 5.1.6 on 2025-05-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_article_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=models.ImageField(null=True, upload_to='wiki_headers/'),
        ),
    ]
