# Generated by Django 5.1.6 on 2025-05-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_articleimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
