# Generated by Django 5.1.6 on 2025-03-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name'], 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
