# Generated by Django 5.1.6 on 2025-04-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0003_alter_producttype_options'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_sale', 'On sale'), ('out_of_stock', 'Out of stock')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on_cart', 'On Cart'), ('to_pay', 'To Pay'), ('to_ship', 'To Ship'), ('to_receive', 'To Receive'), ('delivered', 'Delivered')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.product')),
            ],
        ),
    ]
