# Generated by Django 5.1.6 on 2025-05-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0006_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Sale', 'On sale')], default='available', max_length=20),
        ),
    ]
