# Generated by Django 5.1.6 on 2025-05-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0007_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On Sale', 'On Sale'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On Cart', 'On Cart'), ('To Pay', 'To Pay'), ('To Ship', 'To Ship'), ('To Receive', 'To Receive'), ('Delivered', 'Delivered')], default='On Cart', max_length=20),
        ),
    ]
