# Generated by Django 5.2.1 on 2025-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commission_author_alter_commission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(),
        ),
    ]
